#include <stdio.h>
#include <math.h>
#include <stdlib.h>
#include <assert.h>
#include <stdbool.h>
#include <time.h>
#include "global.c"
#include "error.c"
#include "cursor.c"
#include "list.c"
#include "fn.c"
#include "key.c"
#include "text.c"
#include "print.c"
#include "encode.c"
#include "encrypt.c"
#include "demo.c"
#include "main.c"